# Generated by Django 4.2.7 on 2024-08-14 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_created_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='api.task'),
        ),
    ]
