# Generated by Django 4.2.7 on 2024-08-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_todo_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='to_do_title',
            new_name='title',
        ),
    ]
