# Generated by Django 4.2.7 on 2024-08-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_to_do_title_todo_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='todo',
            name='unqiue_task_to_do',
        ),
        migrations.AddConstraint(
            model_name='todo',
            constraint=models.UniqueConstraint(fields=('task', 'title'), name='unqiue_task_to_do'),
        ),
    ]
